/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _HOLA_H_RPCGEN
#define _HOLA_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct dobleString {
	char *primero;
	char *segundo;
};
typedef struct dobleString dobleString;

#define SERVIDORARCHIVOS 0x20000001
#define SERVIDORARCHIVOSVERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define CREAR 1
extern  int * crear_1(char **, CLIENT *);
extern  int * crear_1_svc(char **, struct svc_req *);
#define ESCRIBIR 2
extern  char ** escribir_1(dobleString *, CLIENT *);
extern  char ** escribir_1_svc(dobleString *, struct svc_req *);
#define LEER 3
extern  char ** leer_1(char **, CLIENT *);
extern  char ** leer_1_svc(char **, struct svc_req *);
#define RENOMBRAR 4
extern  int * renombrar_1(dobleString *, CLIENT *);
extern  int * renombrar_1_svc(dobleString *, struct svc_req *);
#define CREARDIR 5
extern  int * creardir_1(char **, CLIENT *);
extern  int * creardir_1_svc(char **, struct svc_req *);
#define BORRARDIR 6
extern  int * borrardir_1(char **, CLIENT *);
extern  int * borrardir_1_svc(char **, struct svc_req *);
extern int servidorarchivos_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define CREAR 1
extern  int * crear_1();
extern  int * crear_1_svc();
#define ESCRIBIR 2
extern  char ** escribir_1();
extern  char ** escribir_1_svc();
#define LEER 3
extern  char ** leer_1();
extern  char ** leer_1_svc();
#define RENOMBRAR 4
extern  int * renombrar_1();
extern  int * renombrar_1_svc();
#define CREARDIR 5
extern  int * creardir_1();
extern  int * creardir_1_svc();
#define BORRARDIR 6
extern  int * borrardir_1();
extern  int * borrardir_1_svc();
extern int servidorarchivos_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_dobleString (XDR *, dobleString*);

#else /* K&R C */
extern bool_t xdr_dobleString ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_HOLA_H_RPCGEN */
